// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/oniharnantyo/tinyroute/internal/dashboard/components"

type SettingsPageData struct {
	Flash string
	Error string
}

func SettingsPage(data SettingsPageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-6 max-w-xl\"><div><h2 class=\"text-xl font-bold tracking-tight text-white\">Dashboard Settings</h2><p class=\"text-xs text-slate-400\">Manage security options and change administrator password</p></div><!-- Change Password Form --><div class=\"bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6\"><div class=\"border-b border-slate-800 pb-3\"><h3 class=\"font-bold text-sm text-white flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("lock", "w-4 h-4 text-indigo-400").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "Change Dashboard Password</h3><p class=\"text-xs text-slate-400 mt-0.5\">Persisted atomically to <code class=\"px-1 py-0.5 bg-slate-950 rounded border border-slate-800 text-slate-300 font-mono text-[11px]\">~/.tinyroute/dashboard.json</code></p></div><form method=\"POST\" action=\"/dashboard/settings/password\" class=\"space-y-4\"><div class=\"space-y-1.5\"><label for=\"current_password\" class=\"block text-xs font-medium text-slate-300\">Current Password</label> <input type=\"password\" id=\"current_password\" name=\"current_password\" required class=\"w-full px-3.5 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500\"></div><div class=\"space-y-1.5\"><label for=\"new_password\" class=\"block text-xs font-medium text-slate-300\">New Password</label> <input type=\"password\" id=\"new_password\" name=\"new_password\" required minlength=\"6\" class=\"w-full px-3.5 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500\"></div><div class=\"space-y-1.5\"><label for=\"confirm_password\" class=\"block text-xs font-medium text-slate-300\">Confirm New Password</label> <input type=\"password\" id=\"confirm_password\" name=\"confirm_password\" required minlength=\"6\" class=\"w-full px-3.5 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500\"></div><div class=\"pt-2\"><button type=\"submit\" class=\"py-2.5 px-4 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium rounded-xl transition-all shadow-lg shadow-indigo-600/20 flex items-center justify-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("check", "w-4 h-4").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span>Update Password</span></button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
